my_happy_usuario:
    resource: "@MyHappyUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

my_happy_cine_mania:
    resource: "@MyHappyCineManiaBundle/Controller/"
    type:     annotation
    prefix:   /

